// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: myregister.proto

#include "myregister.pb.h"
#include "myregister.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace registerspace {

static const char* MyRegister_method_names[] = {
  "/registerspace.MyRegister/UserRegister",
};

std::unique_ptr< MyRegister::Stub> MyRegister::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MyRegister::Stub> stub(new MyRegister::Stub(channel, options));
  return stub;
}

MyRegister::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UserRegister_(MyRegister_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MyRegister::Stub::UserRegister(::grpc::ClientContext* context, const ::registerspace::UserRegisterRequest& request, ::registerspace::UserRegisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::registerspace::UserRegisterRequest, ::registerspace::UserRegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UserRegister_, context, request, response);
}

void MyRegister::Stub::async::UserRegister(::grpc::ClientContext* context, const ::registerspace::UserRegisterRequest* request, ::registerspace::UserRegisterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::registerspace::UserRegisterRequest, ::registerspace::UserRegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UserRegister_, context, request, response, std::move(f));
}

void MyRegister::Stub::async::UserRegister(::grpc::ClientContext* context, const ::registerspace::UserRegisterRequest* request, ::registerspace::UserRegisterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UserRegister_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::registerspace::UserRegisterReply>* MyRegister::Stub::PrepareAsyncUserRegisterRaw(::grpc::ClientContext* context, const ::registerspace::UserRegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::registerspace::UserRegisterReply, ::registerspace::UserRegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UserRegister_, context, request);
}

::grpc::ClientAsyncResponseReader< ::registerspace::UserRegisterReply>* MyRegister::Stub::AsyncUserRegisterRaw(::grpc::ClientContext* context, const ::registerspace::UserRegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUserRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

MyRegister::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MyRegister_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MyRegister::Service, ::registerspace::UserRegisterRequest, ::registerspace::UserRegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MyRegister::Service* service,
             ::grpc::ServerContext* ctx,
             const ::registerspace::UserRegisterRequest* req,
             ::registerspace::UserRegisterReply* resp) {
               return service->UserRegister(ctx, req, resp);
             }, this)));
}

MyRegister::Service::~Service() {
}

::grpc::Status MyRegister::Service::UserRegister(::grpc::ServerContext* context, const ::registerspace::UserRegisterRequest* request, ::registerspace::UserRegisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace registerspace

